// source: contents/v1/polling.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var contents_v1_article_pb = require('../../contents/v1/article_pb.js');
goog.object.extend(proto, contents_v1_article_pb);
goog.exportSymbol('proto.contents.v1.Polling', null, global);
goog.exportSymbol('proto.contents.v1.PollingCreateRequest', null, global);
goog.exportSymbol('proto.contents.v1.PollingCreateResponse', null, global);
goog.exportSymbol('proto.contents.v1.PollingCreateUpdate', null, global);
goog.exportSymbol('proto.contents.v1.PollingDeleteRequest', null, global);
goog.exportSymbol('proto.contents.v1.PollingDeleteResponse', null, global);
goog.exportSymbol('proto.contents.v1.PollingGetListRequest', null, global);
goog.exportSymbol('proto.contents.v1.PollingGetListRequest.Sort', null, global);
goog.exportSymbol('proto.contents.v1.PollingGetListResponse', null, global);
goog.exportSymbol('proto.contents.v1.PollingGetOneRequest', null, global);
goog.exportSymbol('proto.contents.v1.PollingGetOneResponse', null, global);
goog.exportSymbol('proto.contents.v1.PollingStatus', null, global);
goog.exportSymbol('proto.contents.v1.PollingUpdateRequest', null, global);
goog.exportSymbol('proto.contents.v1.PollingUpdateResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contents.v1.Polling = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contents.v1.Polling, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contents.v1.Polling.displayName = 'proto.contents.v1.Polling';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contents.v1.PollingCreateUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contents.v1.PollingCreateUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contents.v1.PollingCreateUpdate.displayName = 'proto.contents.v1.PollingCreateUpdate';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contents.v1.PollingGetOneRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contents.v1.PollingGetOneRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contents.v1.PollingGetOneRequest.displayName = 'proto.contents.v1.PollingGetOneRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contents.v1.PollingGetOneResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contents.v1.PollingGetOneResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contents.v1.PollingGetOneResponse.displayName = 'proto.contents.v1.PollingGetOneResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contents.v1.PollingGetListRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.contents.v1.PollingGetListRequest.repeatedFields_, null);
};
goog.inherits(proto.contents.v1.PollingGetListRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contents.v1.PollingGetListRequest.displayName = 'proto.contents.v1.PollingGetListRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contents.v1.PollingGetListResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.contents.v1.PollingGetListResponse.repeatedFields_, null);
};
goog.inherits(proto.contents.v1.PollingGetListResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contents.v1.PollingGetListResponse.displayName = 'proto.contents.v1.PollingGetListResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contents.v1.PollingCreateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contents.v1.PollingCreateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contents.v1.PollingCreateRequest.displayName = 'proto.contents.v1.PollingCreateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contents.v1.PollingCreateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contents.v1.PollingCreateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contents.v1.PollingCreateResponse.displayName = 'proto.contents.v1.PollingCreateResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contents.v1.PollingUpdateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contents.v1.PollingUpdateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contents.v1.PollingUpdateRequest.displayName = 'proto.contents.v1.PollingUpdateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contents.v1.PollingUpdateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contents.v1.PollingUpdateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contents.v1.PollingUpdateResponse.displayName = 'proto.contents.v1.PollingUpdateResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contents.v1.PollingDeleteRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contents.v1.PollingDeleteRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contents.v1.PollingDeleteRequest.displayName = 'proto.contents.v1.PollingDeleteRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.contents.v1.PollingDeleteResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.contents.v1.PollingDeleteResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.contents.v1.PollingDeleteResponse.displayName = 'proto.contents.v1.PollingDeleteResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contents.v1.Polling.prototype.toObject = function(opt_includeInstance) {
  return proto.contents.v1.Polling.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contents.v1.Polling} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.Polling.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    status: jspb.Message.getFieldWithDefault(msg, 3, 0),
    imageCoverUrl: jspb.Message.getFieldWithDefault(msg, 15, ""),
    imageCoverAlt: jspb.Message.getFieldWithDefault(msg, 16, ""),
    choice1Label: jspb.Message.getFieldWithDefault(msg, 4, ""),
    choice1ArticleId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    choice1Count: jspb.Message.getFieldWithDefault(msg, 13, 0),
    choice2Label: jspb.Message.getFieldWithDefault(msg, 6, ""),
    choice2ArticleId: jspb.Message.getFieldWithDefault(msg, 7, 0),
    choice2Count: jspb.Message.getFieldWithDefault(msg, 14, 0),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    publishedAt: (f = msg.getPublishedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    choice1Article: (f = msg.getChoice1Article()) && contents_v1_article_pb.Article.toObject(includeInstance, f),
    choice2Article: (f = msg.getChoice2Article()) && contents_v1_article_pb.Article.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contents.v1.Polling}
 */
proto.contents.v1.Polling.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contents.v1.Polling;
  return proto.contents.v1.Polling.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contents.v1.Polling} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contents.v1.Polling}
 */
proto.contents.v1.Polling.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {!proto.contents.v1.PollingStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageCoverUrl(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageCoverAlt(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setChoice1Label(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChoice1ArticleId(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChoice1Count(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setChoice2Label(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChoice2ArticleId(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChoice2Count(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setPublishedAt(value);
      break;
    case 11:
      var value = new contents_v1_article_pb.Article;
      reader.readMessage(value,contents_v1_article_pb.Article.deserializeBinaryFromReader);
      msg.setChoice1Article(value);
      break;
    case 12:
      var value = new contents_v1_article_pb.Article;
      reader.readMessage(value,contents_v1_article_pb.Article.deserializeBinaryFromReader);
      msg.setChoice2Article(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contents.v1.Polling.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contents.v1.Polling.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contents.v1.Polling} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.Polling.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getImageCoverUrl();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getImageCoverAlt();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getChoice1Label();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getChoice1ArticleId();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getChoice1Count();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getChoice2Label();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getChoice2ArticleId();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getChoice2Count();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getPublishedAt();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getChoice1Article();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      contents_v1_article_pb.Article.serializeBinaryToWriter
    );
  }
  f = message.getChoice2Article();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      contents_v1_article_pb.Article.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.contents.v1.Polling.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.contents.v1.Polling.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional PollingStatus status = 3;
 * @return {!proto.contents.v1.PollingStatus}
 */
proto.contents.v1.Polling.prototype.getStatus = function() {
  return /** @type {!proto.contents.v1.PollingStatus} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.contents.v1.PollingStatus} value
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional string image_cover_url = 15;
 * @return {string}
 */
proto.contents.v1.Polling.prototype.getImageCoverUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.setImageCoverUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string image_cover_alt = 16;
 * @return {string}
 */
proto.contents.v1.Polling.prototype.getImageCoverAlt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.setImageCoverAlt = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional string choice_1_label = 4;
 * @return {string}
 */
proto.contents.v1.Polling.prototype.getChoice1Label = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.setChoice1Label = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 choice_1_article_id = 5;
 * @return {number}
 */
proto.contents.v1.Polling.prototype.getChoice1ArticleId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.setChoice1ArticleId = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 choice_1_count = 13;
 * @return {number}
 */
proto.contents.v1.Polling.prototype.getChoice1Count = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.setChoice1Count = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional string choice_2_label = 6;
 * @return {string}
 */
proto.contents.v1.Polling.prototype.getChoice2Label = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.setChoice2Label = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int32 choice_2_article_id = 7;
 * @return {number}
 */
proto.contents.v1.Polling.prototype.getChoice2ArticleId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.setChoice2ArticleId = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 choice_2_count = 14;
 * @return {number}
 */
proto.contents.v1.Polling.prototype.getChoice2Count = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.setChoice2Count = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.contents.v1.Polling.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.contents.v1.Polling} returns this
*/
proto.contents.v1.Polling.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contents.v1.Polling.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.contents.v1.Polling.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.contents.v1.Polling} returns this
*/
proto.contents.v1.Polling.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contents.v1.Polling.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.Timestamp published_at = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.contents.v1.Polling.prototype.getPublishedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.contents.v1.Polling} returns this
*/
proto.contents.v1.Polling.prototype.setPublishedAt = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.clearPublishedAt = function() {
  return this.setPublishedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contents.v1.Polling.prototype.hasPublishedAt = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional Article choice_1_article = 11;
 * @return {?proto.contents.v1.Article}
 */
proto.contents.v1.Polling.prototype.getChoice1Article = function() {
  return /** @type{?proto.contents.v1.Article} */ (
    jspb.Message.getWrapperField(this, contents_v1_article_pb.Article, 11));
};


/**
 * @param {?proto.contents.v1.Article|undefined} value
 * @return {!proto.contents.v1.Polling} returns this
*/
proto.contents.v1.Polling.prototype.setChoice1Article = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.clearChoice1Article = function() {
  return this.setChoice1Article(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contents.v1.Polling.prototype.hasChoice1Article = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional Article choice_2_article = 12;
 * @return {?proto.contents.v1.Article}
 */
proto.contents.v1.Polling.prototype.getChoice2Article = function() {
  return /** @type{?proto.contents.v1.Article} */ (
    jspb.Message.getWrapperField(this, contents_v1_article_pb.Article, 12));
};


/**
 * @param {?proto.contents.v1.Article|undefined} value
 * @return {!proto.contents.v1.Polling} returns this
*/
proto.contents.v1.Polling.prototype.setChoice2Article = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.contents.v1.Polling} returns this
 */
proto.contents.v1.Polling.prototype.clearChoice2Article = function() {
  return this.setChoice2Article(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contents.v1.Polling.prototype.hasChoice2Article = function() {
  return jspb.Message.getField(this, 12) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contents.v1.PollingCreateUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.contents.v1.PollingCreateUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contents.v1.PollingCreateUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingCreateUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    status: jspb.Message.getFieldWithDefault(msg, 3, 0),
    imageCoverUrl: jspb.Message.getFieldWithDefault(msg, 15, ""),
    imageCoverAlt: jspb.Message.getFieldWithDefault(msg, 16, ""),
    choice1Label: jspb.Message.getFieldWithDefault(msg, 4, ""),
    choice1ArticleId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    choice2Label: jspb.Message.getFieldWithDefault(msg, 6, ""),
    choice2ArticleId: jspb.Message.getFieldWithDefault(msg, 7, 0),
    isCustomPublishedAt: jspb.Message.getBooleanFieldWithDefault(msg, 13, false),
    publishedAt: (f = msg.getPublishedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contents.v1.PollingCreateUpdate}
 */
proto.contents.v1.PollingCreateUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contents.v1.PollingCreateUpdate;
  return proto.contents.v1.PollingCreateUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contents.v1.PollingCreateUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contents.v1.PollingCreateUpdate}
 */
proto.contents.v1.PollingCreateUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {!proto.contents.v1.PollingStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageCoverUrl(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageCoverAlt(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setChoice1Label(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChoice1ArticleId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setChoice2Label(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChoice2ArticleId(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsCustomPublishedAt(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setPublishedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contents.v1.PollingCreateUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contents.v1.PollingCreateUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contents.v1.PollingCreateUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingCreateUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getImageCoverUrl();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getImageCoverAlt();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getChoice1Label();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getChoice1ArticleId();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getChoice2Label();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getChoice2ArticleId();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getIsCustomPublishedAt();
  if (f) {
    writer.writeBool(
      13,
      f
    );
  }
  f = message.getPublishedAt();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.contents.v1.PollingCreateUpdate.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.contents.v1.PollingCreateUpdate} returns this
 */
proto.contents.v1.PollingCreateUpdate.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional PollingStatus status = 3;
 * @return {!proto.contents.v1.PollingStatus}
 */
proto.contents.v1.PollingCreateUpdate.prototype.getStatus = function() {
  return /** @type {!proto.contents.v1.PollingStatus} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.contents.v1.PollingStatus} value
 * @return {!proto.contents.v1.PollingCreateUpdate} returns this
 */
proto.contents.v1.PollingCreateUpdate.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional string image_cover_url = 15;
 * @return {string}
 */
proto.contents.v1.PollingCreateUpdate.prototype.getImageCoverUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.contents.v1.PollingCreateUpdate} returns this
 */
proto.contents.v1.PollingCreateUpdate.prototype.setImageCoverUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string image_cover_alt = 16;
 * @return {string}
 */
proto.contents.v1.PollingCreateUpdate.prototype.getImageCoverAlt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.contents.v1.PollingCreateUpdate} returns this
 */
proto.contents.v1.PollingCreateUpdate.prototype.setImageCoverAlt = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional string choice_1_label = 4;
 * @return {string}
 */
proto.contents.v1.PollingCreateUpdate.prototype.getChoice1Label = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.contents.v1.PollingCreateUpdate} returns this
 */
proto.contents.v1.PollingCreateUpdate.prototype.setChoice1Label = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 choice_1_article_id = 5;
 * @return {number}
 */
proto.contents.v1.PollingCreateUpdate.prototype.getChoice1ArticleId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.PollingCreateUpdate} returns this
 */
proto.contents.v1.PollingCreateUpdate.prototype.setChoice1ArticleId = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string choice_2_label = 6;
 * @return {string}
 */
proto.contents.v1.PollingCreateUpdate.prototype.getChoice2Label = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.contents.v1.PollingCreateUpdate} returns this
 */
proto.contents.v1.PollingCreateUpdate.prototype.setChoice2Label = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int32 choice_2_article_id = 7;
 * @return {number}
 */
proto.contents.v1.PollingCreateUpdate.prototype.getChoice2ArticleId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.PollingCreateUpdate} returns this
 */
proto.contents.v1.PollingCreateUpdate.prototype.setChoice2ArticleId = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional bool is_custom_published_at = 13;
 * @return {boolean}
 */
proto.contents.v1.PollingCreateUpdate.prototype.getIsCustomPublishedAt = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/**
 * @param {boolean} value
 * @return {!proto.contents.v1.PollingCreateUpdate} returns this
 */
proto.contents.v1.PollingCreateUpdate.prototype.setIsCustomPublishedAt = function(value) {
  return jspb.Message.setProto3BooleanField(this, 13, value);
};


/**
 * optional google.protobuf.Timestamp published_at = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.contents.v1.PollingCreateUpdate.prototype.getPublishedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.contents.v1.PollingCreateUpdate} returns this
*/
proto.contents.v1.PollingCreateUpdate.prototype.setPublishedAt = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.contents.v1.PollingCreateUpdate} returns this
 */
proto.contents.v1.PollingCreateUpdate.prototype.clearPublishedAt = function() {
  return this.setPublishedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contents.v1.PollingCreateUpdate.prototype.hasPublishedAt = function() {
  return jspb.Message.getField(this, 10) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contents.v1.PollingGetOneRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.contents.v1.PollingGetOneRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contents.v1.PollingGetOneRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingGetOneRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contents.v1.PollingGetOneRequest}
 */
proto.contents.v1.PollingGetOneRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contents.v1.PollingGetOneRequest;
  return proto.contents.v1.PollingGetOneRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contents.v1.PollingGetOneRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contents.v1.PollingGetOneRequest}
 */
proto.contents.v1.PollingGetOneRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contents.v1.PollingGetOneRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contents.v1.PollingGetOneRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contents.v1.PollingGetOneRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingGetOneRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.contents.v1.PollingGetOneRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.PollingGetOneRequest} returns this
 */
proto.contents.v1.PollingGetOneRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contents.v1.PollingGetOneResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.contents.v1.PollingGetOneResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contents.v1.PollingGetOneResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingGetOneResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    polling: (f = msg.getPolling()) && proto.contents.v1.Polling.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contents.v1.PollingGetOneResponse}
 */
proto.contents.v1.PollingGetOneResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contents.v1.PollingGetOneResponse;
  return proto.contents.v1.PollingGetOneResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contents.v1.PollingGetOneResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contents.v1.PollingGetOneResponse}
 */
proto.contents.v1.PollingGetOneResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.contents.v1.Polling;
      reader.readMessage(value,proto.contents.v1.Polling.deserializeBinaryFromReader);
      msg.setPolling(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contents.v1.PollingGetOneResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contents.v1.PollingGetOneResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contents.v1.PollingGetOneResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingGetOneResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPolling();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.contents.v1.Polling.serializeBinaryToWriter
    );
  }
};


/**
 * optional Polling polling = 1;
 * @return {?proto.contents.v1.Polling}
 */
proto.contents.v1.PollingGetOneResponse.prototype.getPolling = function() {
  return /** @type{?proto.contents.v1.Polling} */ (
    jspb.Message.getWrapperField(this, proto.contents.v1.Polling, 1));
};


/**
 * @param {?proto.contents.v1.Polling|undefined} value
 * @return {!proto.contents.v1.PollingGetOneResponse} returns this
*/
proto.contents.v1.PollingGetOneResponse.prototype.setPolling = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.contents.v1.PollingGetOneResponse} returns this
 */
proto.contents.v1.PollingGetOneResponse.prototype.clearPolling = function() {
  return this.setPolling(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contents.v1.PollingGetOneResponse.prototype.hasPolling = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.contents.v1.PollingGetListRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contents.v1.PollingGetListRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.contents.v1.PollingGetListRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contents.v1.PollingGetListRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingGetListRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    statusMultipleList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    search: jspb.Message.getFieldWithDefault(msg, 2, ""),
    page: jspb.Message.getFieldWithDefault(msg, 3, 0),
    contentPerPage: jspb.Message.getFieldWithDefault(msg, 4, 0),
    sortBy: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contents.v1.PollingGetListRequest}
 */
proto.contents.v1.PollingGetListRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contents.v1.PollingGetListRequest;
  return proto.contents.v1.PollingGetListRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contents.v1.PollingGetListRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contents.v1.PollingGetListRequest}
 */
proto.contents.v1.PollingGetListRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<!proto.contents.v1.PollingStatus>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addStatusMultiple(values[i]);
      }
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSearch(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPage(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setContentPerPage(value);
      break;
    case 5:
      var value = /** @type {!proto.contents.v1.PollingGetListRequest.Sort} */ (reader.readEnum());
      msg.setSortBy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contents.v1.PollingGetListRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contents.v1.PollingGetListRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contents.v1.PollingGetListRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingGetListRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatusMultipleList();
  if (f.length > 0) {
    writer.writePackedEnum(
      1,
      f
    );
  }
  f = message.getSearch();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPage();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getContentPerPage();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSortBy();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.contents.v1.PollingGetListRequest.Sort = {
  NEWEST_UNSPECIFIED: 0,
  OLDEST: 1,
  TITLE_ASCENDING: 2,
  TITLE_DESCENDING: 3,
  CREATED_AT_ASCENDING: 6,
  CREATED_AT_DESCENDING: 7,
  PUBLISHED_AT_ASCENDING: 8,
  PUBLISHED_AT_DESCENDING: 9
};

/**
 * repeated PollingStatus status_multiple = 1;
 * @return {!Array<!proto.contents.v1.PollingStatus>}
 */
proto.contents.v1.PollingGetListRequest.prototype.getStatusMultipleList = function() {
  return /** @type {!Array<!proto.contents.v1.PollingStatus>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<!proto.contents.v1.PollingStatus>} value
 * @return {!proto.contents.v1.PollingGetListRequest} returns this
 */
proto.contents.v1.PollingGetListRequest.prototype.setStatusMultipleList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!proto.contents.v1.PollingStatus} value
 * @param {number=} opt_index
 * @return {!proto.contents.v1.PollingGetListRequest} returns this
 */
proto.contents.v1.PollingGetListRequest.prototype.addStatusMultiple = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.contents.v1.PollingGetListRequest} returns this
 */
proto.contents.v1.PollingGetListRequest.prototype.clearStatusMultipleList = function() {
  return this.setStatusMultipleList([]);
};


/**
 * optional string search = 2;
 * @return {string}
 */
proto.contents.v1.PollingGetListRequest.prototype.getSearch = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.contents.v1.PollingGetListRequest} returns this
 */
proto.contents.v1.PollingGetListRequest.prototype.setSearch = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 page = 3;
 * @return {number}
 */
proto.contents.v1.PollingGetListRequest.prototype.getPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.PollingGetListRequest} returns this
 */
proto.contents.v1.PollingGetListRequest.prototype.setPage = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 content_per_page = 4;
 * @return {number}
 */
proto.contents.v1.PollingGetListRequest.prototype.getContentPerPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.PollingGetListRequest} returns this
 */
proto.contents.v1.PollingGetListRequest.prototype.setContentPerPage = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional Sort sort_by = 5;
 * @return {!proto.contents.v1.PollingGetListRequest.Sort}
 */
proto.contents.v1.PollingGetListRequest.prototype.getSortBy = function() {
  return /** @type {!proto.contents.v1.PollingGetListRequest.Sort} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.contents.v1.PollingGetListRequest.Sort} value
 * @return {!proto.contents.v1.PollingGetListRequest} returns this
 */
proto.contents.v1.PollingGetListRequest.prototype.setSortBy = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.contents.v1.PollingGetListResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contents.v1.PollingGetListResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.contents.v1.PollingGetListResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contents.v1.PollingGetListResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingGetListResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    dataList: jspb.Message.toObjectList(msg.getDataList(),
    proto.contents.v1.Polling.toObject, includeInstance),
    maxPage: jspb.Message.getFieldWithDefault(msg, 2, 0),
    count: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contents.v1.PollingGetListResponse}
 */
proto.contents.v1.PollingGetListResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contents.v1.PollingGetListResponse;
  return proto.contents.v1.PollingGetListResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contents.v1.PollingGetListResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contents.v1.PollingGetListResponse}
 */
proto.contents.v1.PollingGetListResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.contents.v1.Polling;
      reader.readMessage(value,proto.contents.v1.Polling.deserializeBinaryFromReader);
      msg.addData(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxPage(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contents.v1.PollingGetListResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contents.v1.PollingGetListResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contents.v1.PollingGetListResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingGetListResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.contents.v1.Polling.serializeBinaryToWriter
    );
  }
  f = message.getMaxPage();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getCount();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * repeated Polling data = 1;
 * @return {!Array<!proto.contents.v1.Polling>}
 */
proto.contents.v1.PollingGetListResponse.prototype.getDataList = function() {
  return /** @type{!Array<!proto.contents.v1.Polling>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.contents.v1.Polling, 1));
};


/**
 * @param {!Array<!proto.contents.v1.Polling>} value
 * @return {!proto.contents.v1.PollingGetListResponse} returns this
*/
proto.contents.v1.PollingGetListResponse.prototype.setDataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.contents.v1.Polling=} opt_value
 * @param {number=} opt_index
 * @return {!proto.contents.v1.Polling}
 */
proto.contents.v1.PollingGetListResponse.prototype.addData = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.contents.v1.Polling, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.contents.v1.PollingGetListResponse} returns this
 */
proto.contents.v1.PollingGetListResponse.prototype.clearDataList = function() {
  return this.setDataList([]);
};


/**
 * optional int32 max_page = 2;
 * @return {number}
 */
proto.contents.v1.PollingGetListResponse.prototype.getMaxPage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.PollingGetListResponse} returns this
 */
proto.contents.v1.PollingGetListResponse.prototype.setMaxPage = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 count = 3;
 * @return {number}
 */
proto.contents.v1.PollingGetListResponse.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.PollingGetListResponse} returns this
 */
proto.contents.v1.PollingGetListResponse.prototype.setCount = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contents.v1.PollingCreateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.contents.v1.PollingCreateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contents.v1.PollingCreateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingCreateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: (f = msg.getData()) && proto.contents.v1.PollingCreateUpdate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contents.v1.PollingCreateRequest}
 */
proto.contents.v1.PollingCreateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contents.v1.PollingCreateRequest;
  return proto.contents.v1.PollingCreateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contents.v1.PollingCreateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contents.v1.PollingCreateRequest}
 */
proto.contents.v1.PollingCreateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.contents.v1.PollingCreateUpdate;
      reader.readMessage(value,proto.contents.v1.PollingCreateUpdate.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contents.v1.PollingCreateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contents.v1.PollingCreateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contents.v1.PollingCreateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingCreateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.contents.v1.PollingCreateUpdate.serializeBinaryToWriter
    );
  }
};


/**
 * optional PollingCreateUpdate data = 1;
 * @return {?proto.contents.v1.PollingCreateUpdate}
 */
proto.contents.v1.PollingCreateRequest.prototype.getData = function() {
  return /** @type{?proto.contents.v1.PollingCreateUpdate} */ (
    jspb.Message.getWrapperField(this, proto.contents.v1.PollingCreateUpdate, 1));
};


/**
 * @param {?proto.contents.v1.PollingCreateUpdate|undefined} value
 * @return {!proto.contents.v1.PollingCreateRequest} returns this
*/
proto.contents.v1.PollingCreateRequest.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.contents.v1.PollingCreateRequest} returns this
 */
proto.contents.v1.PollingCreateRequest.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contents.v1.PollingCreateRequest.prototype.hasData = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contents.v1.PollingCreateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.contents.v1.PollingCreateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contents.v1.PollingCreateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingCreateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: (f = msg.getData()) && proto.contents.v1.Polling.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contents.v1.PollingCreateResponse}
 */
proto.contents.v1.PollingCreateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contents.v1.PollingCreateResponse;
  return proto.contents.v1.PollingCreateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contents.v1.PollingCreateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contents.v1.PollingCreateResponse}
 */
proto.contents.v1.PollingCreateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.contents.v1.Polling;
      reader.readMessage(value,proto.contents.v1.Polling.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contents.v1.PollingCreateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contents.v1.PollingCreateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contents.v1.PollingCreateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingCreateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.contents.v1.Polling.serializeBinaryToWriter
    );
  }
};


/**
 * optional Polling data = 1;
 * @return {?proto.contents.v1.Polling}
 */
proto.contents.v1.PollingCreateResponse.prototype.getData = function() {
  return /** @type{?proto.contents.v1.Polling} */ (
    jspb.Message.getWrapperField(this, proto.contents.v1.Polling, 1));
};


/**
 * @param {?proto.contents.v1.Polling|undefined} value
 * @return {!proto.contents.v1.PollingCreateResponse} returns this
*/
proto.contents.v1.PollingCreateResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.contents.v1.PollingCreateResponse} returns this
 */
proto.contents.v1.PollingCreateResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contents.v1.PollingCreateResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contents.v1.PollingUpdateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.contents.v1.PollingUpdateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contents.v1.PollingUpdateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingUpdateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    data: (f = msg.getData()) && proto.contents.v1.PollingCreateUpdate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contents.v1.PollingUpdateRequest}
 */
proto.contents.v1.PollingUpdateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contents.v1.PollingUpdateRequest;
  return proto.contents.v1.PollingUpdateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contents.v1.PollingUpdateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contents.v1.PollingUpdateRequest}
 */
proto.contents.v1.PollingUpdateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.contents.v1.PollingCreateUpdate;
      reader.readMessage(value,proto.contents.v1.PollingCreateUpdate.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contents.v1.PollingUpdateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contents.v1.PollingUpdateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contents.v1.PollingUpdateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingUpdateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.contents.v1.PollingCreateUpdate.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.contents.v1.PollingUpdateRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.PollingUpdateRequest} returns this
 */
proto.contents.v1.PollingUpdateRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional PollingCreateUpdate data = 2;
 * @return {?proto.contents.v1.PollingCreateUpdate}
 */
proto.contents.v1.PollingUpdateRequest.prototype.getData = function() {
  return /** @type{?proto.contents.v1.PollingCreateUpdate} */ (
    jspb.Message.getWrapperField(this, proto.contents.v1.PollingCreateUpdate, 2));
};


/**
 * @param {?proto.contents.v1.PollingCreateUpdate|undefined} value
 * @return {!proto.contents.v1.PollingUpdateRequest} returns this
*/
proto.contents.v1.PollingUpdateRequest.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.contents.v1.PollingUpdateRequest} returns this
 */
proto.contents.v1.PollingUpdateRequest.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contents.v1.PollingUpdateRequest.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contents.v1.PollingUpdateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.contents.v1.PollingUpdateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contents.v1.PollingUpdateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingUpdateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: (f = msg.getData()) && proto.contents.v1.Polling.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contents.v1.PollingUpdateResponse}
 */
proto.contents.v1.PollingUpdateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contents.v1.PollingUpdateResponse;
  return proto.contents.v1.PollingUpdateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contents.v1.PollingUpdateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contents.v1.PollingUpdateResponse}
 */
proto.contents.v1.PollingUpdateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.contents.v1.Polling;
      reader.readMessage(value,proto.contents.v1.Polling.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contents.v1.PollingUpdateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contents.v1.PollingUpdateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contents.v1.PollingUpdateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingUpdateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.contents.v1.Polling.serializeBinaryToWriter
    );
  }
};


/**
 * optional Polling data = 1;
 * @return {?proto.contents.v1.Polling}
 */
proto.contents.v1.PollingUpdateResponse.prototype.getData = function() {
  return /** @type{?proto.contents.v1.Polling} */ (
    jspb.Message.getWrapperField(this, proto.contents.v1.Polling, 1));
};


/**
 * @param {?proto.contents.v1.Polling|undefined} value
 * @return {!proto.contents.v1.PollingUpdateResponse} returns this
*/
proto.contents.v1.PollingUpdateResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.contents.v1.PollingUpdateResponse} returns this
 */
proto.contents.v1.PollingUpdateResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contents.v1.PollingUpdateResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contents.v1.PollingDeleteRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.contents.v1.PollingDeleteRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contents.v1.PollingDeleteRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingDeleteRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    softDelete: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contents.v1.PollingDeleteRequest}
 */
proto.contents.v1.PollingDeleteRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contents.v1.PollingDeleteRequest;
  return proto.contents.v1.PollingDeleteRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contents.v1.PollingDeleteRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contents.v1.PollingDeleteRequest}
 */
proto.contents.v1.PollingDeleteRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSoftDelete(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contents.v1.PollingDeleteRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contents.v1.PollingDeleteRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contents.v1.PollingDeleteRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingDeleteRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSoftDelete();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.contents.v1.PollingDeleteRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.contents.v1.PollingDeleteRequest} returns this
 */
proto.contents.v1.PollingDeleteRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool soft_delete = 2;
 * @return {boolean}
 */
proto.contents.v1.PollingDeleteRequest.prototype.getSoftDelete = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.contents.v1.PollingDeleteRequest} returns this
 */
proto.contents.v1.PollingDeleteRequest.prototype.setSoftDelete = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.contents.v1.PollingDeleteResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.contents.v1.PollingDeleteResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.contents.v1.PollingDeleteResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingDeleteResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: (f = msg.getData()) && proto.contents.v1.Polling.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.contents.v1.PollingDeleteResponse}
 */
proto.contents.v1.PollingDeleteResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.contents.v1.PollingDeleteResponse;
  return proto.contents.v1.PollingDeleteResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.contents.v1.PollingDeleteResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.contents.v1.PollingDeleteResponse}
 */
proto.contents.v1.PollingDeleteResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.contents.v1.Polling;
      reader.readMessage(value,proto.contents.v1.Polling.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.contents.v1.PollingDeleteResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.contents.v1.PollingDeleteResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.contents.v1.PollingDeleteResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.contents.v1.PollingDeleteResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.contents.v1.Polling.serializeBinaryToWriter
    );
  }
};


/**
 * optional Polling data = 1;
 * @return {?proto.contents.v1.Polling}
 */
proto.contents.v1.PollingDeleteResponse.prototype.getData = function() {
  return /** @type{?proto.contents.v1.Polling} */ (
    jspb.Message.getWrapperField(this, proto.contents.v1.Polling, 1));
};


/**
 * @param {?proto.contents.v1.Polling|undefined} value
 * @return {!proto.contents.v1.PollingDeleteResponse} returns this
*/
proto.contents.v1.PollingDeleteResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.contents.v1.PollingDeleteResponse} returns this
 */
proto.contents.v1.PollingDeleteResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.contents.v1.PollingDeleteResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * @enum {number}
 */
proto.contents.v1.PollingStatus = {
  POLLING_STATUS_ALL_UNSPECIFIED: 0,
  POLLING_STATUS_DRAFT: 1,
  POLLING_STATUS_TRASH: 2,
  POLLING_STATUS_PUBLISH: 3,
  POLLING_STATUS_COMING_SOON: 4
};

goog.object.extend(exports, proto.contents.v1);
